"""removed unique=True from text column

Revision ID: 358d8ad95f1c
Revises: 4ed9313951c6
Create Date: 2026-01-20 02:50:13.780645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358d8ad95f1c'
down_revision: Union[str, Sequence[str], None] = '4ed9313951c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_post_text'), 'post', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_post_text'), 'post', ['text'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
